import { jsPDF } from "jspdf";
import { AnalysisResult } from "../types";

export const generatePDF = (data: AnalysisResult) => {
  const doc = new jsPDF();
  const margin = 20;
  let y = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxLineWidth = pageWidth - margin * 2;

  // Helpers
  const addTitle = (text: string) => {
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 102, 204); // Medical Blue
    doc.text(text, margin, y);
    y += 15;
  };

  const addSubtitle = (text: string) => {
    // Check page break
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(51, 65, 85); // Slate 700
    doc.text(text, margin, y);
    y += 8;
  };

  const addBody = (text: string, isBold = false, color = [30, 41, 59]) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxLineWidth);
    
    if (y + lines.length * 5 > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
    
    doc.text(lines, margin, y);
    y += lines.length * 5 + 3;
  };

  const addSpacing = (amount: number = 5) => {
    y += amount;
  };

  // --- Content Generation ---

  // Header
  addTitle("MediScan Pro+ | Clinical Insight Report");
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 10;
  
  // Triage Banner
  doc.setFillColor(
    data.triageLevel === 'Critical' ? 220 : data.triageLevel === 'High' ? 251 : 254, 
    data.triageLevel === 'Critical' ? 38 : data.triageLevel === 'High' ? 146 : 243, 
    data.triageLevel === 'Critical' ? 38 : data.triageLevel === 'High' ? 60 : 199
  ); 
  doc.rect(margin, y, maxLineWidth, 14, 'F');
  doc.setTextColor(50);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`TRIAGE LEVEL: ${data.triageLevel.toUpperCase()}`, margin + 5, y + 9);
  y += 24;

  // Radar Score Summary (Textual)
  addSubtitle("Health Radar Score (AI Estimates 0-100)");
  const radarText = `Hydration: ${data.healthRadar.hydration} | Fatigue: ${data.healthRadar.fatigue} | Stress: ${data.healthRadar.stress} | Inflammation: ${data.healthRadar.inflammation} | Severity: ${data.healthRadar.severity}`;
  addBody(radarText, true);
  addSpacing();

  // Sections
  addSubtitle("Chief Complaint");
  addBody(data.chiefComplaint);
  
  if (data.timelineAnalysis) {
    addSubtitle("Timeline & Trend Analysis");
    addBody(data.timelineAnalysis);
  }

  if (data.voiceSummary) {
    addSubtitle("Voice Note Summary");
    addBody(data.voiceSummary);
  }

  if (data.visualObservations) {
    addSubtitle("Visual Observations");
    addBody(data.visualObservations);
  }

  if (data.imageComparison) {
    addSubtitle("Comparative Analysis (Day 1 vs Day X)");
    addBody(data.imageComparison);
  }

  if (data.medicineAnalysis) {
    addSubtitle("Medicine Identification (Safe Mode)");
    addBody(data.medicineAnalysis);
    addBody("Disclaimer: Identification is tentative. Do not change medication without doctor approval.", false, [150, 0, 0]);
  }

  addSubtitle("Symptom Analysis");
  addBody(data.symptomAnalysis);
  
  addSubtitle("AI Reasoning");
  addBody(data.triageReasoning, false, [70, 70, 70]);

  if (data.redFlags && data.redFlags.length > 0) {
    addSubtitle("RED FLAGS (Urgent)");
    data.redFlags.forEach(flag => addBody(`• ${flag}`, true, [200, 0, 0]));
  }

  addSubtitle("Differential Considerations");
  data.differentials.forEach(diff => addBody(`• ${diff}`));

  addSubtitle("Home Care Recommendations");
  data.homeCare.forEach(item => addBody(`• ${item}`));
  addSpacing(10);

  // SOAP NOTE
  doc.addPage();
  y = 20;
  addTitle("Clinician Structured Note (SOAP)");
  
  addSubtitle("Subjective");
  addBody(data.soap.subjective);

  addSubtitle("Objective");
  addBody(data.soap.objective);

  addSubtitle("Assessment");
  addBody(data.soap.assessment);

  addSubtitle("Plan");
  addBody(data.soap.plan);
  addSpacing(20);

  // Disclaimer
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(150);
  const disclaimer = "DISCLAIMER: This document is generated by MediScan Pro+ AI. It is for informational purposes only and does NOT constitute a medical diagnosis, advice, or treatment plan. Always seek the advice of a physician or other qualified health provider with any questions you may have regarding a medical condition. If you think you may have a medical emergency, call your doctor or emergency services immediately.";
  const disclaimerLines = doc.splitTextToSize(disclaimer, maxLineWidth);
  doc.text(disclaimerLines, margin, y);

  // Save
  doc.save("MediScan_Pro_Plus_Report.pdf");
};